### PR TITLE
WIP Queensland adapter

### PR DESCRIPTION
**Pull request by dolugen**
#145

### CODE REVIEW

**Comment by dolugen** [comment]
Wanna go forward with this, but I'm a bit stuck on naming the cities. See #251 for details.

**Comment by jflasher** [comment]
@dolugen I think for the cities part, we can just go with the `region` field in the XML? We've done similar elsewhere.
```xml
<region name="South East Queensland" information="http://www.qld.gov.au/environment/pollution/monitoring/air-monitoring/seq/">
```

**Comment by dolugen** [comment]
All right, sounds good to me. I'll continue like that.

**Comment by jflasher** [comment]
Thanks! Got lots of stuff to check out and merge once I get the EEA thing cleared up (hopefully this weekend).

**Pull request merged**
