### PR TITLE
Delhi Pollution Control Committee: National Capital Territory (NCT)

### PR DESCRIPTION
**Pull request by majesticio**
This adapter adds `24` stations from Delhi (NCT). Data is retrieved using puppeteer, and can take anywhere from 1 to 3.5 minutes to fetch the data. A deployment has been added so this adapter will run on its own and not with the realtime deployment. This adapter fetches these parameters from each station: `co, no2, o3 , so2, pm25` in `µg/m³`, and relative humidity in `%`. Stations are fetched dynamically.

### CODE REVIEW

**Review by caparker — CHANGES_REQUESTED** [review]
A couple of things before I can check this
- I am getting an error that `Highcharts` is not defined
- Why is it using a deprecated version of puppeteer?

**Comment by majesticio** [comment]
I have updated the adapter to use the latest version of puppeteer as requested. The code now reflects recent changes to the puppeteer API.

**Review by caparker — CHANGES_REQUESTED** [review]
I love the doc strings but those are the only changes I am seeing here. Did you commit the puppeteer update?

**Comment by majesticio** [comment]
Good catch, it should now have `"puppeteer": "^22.5.0"`

**Review by caparker — CHANGES_REQUESTED** [review]
I am still running into a bunch of issues

- The log.info, log.error etc only take one parameter, they dont work the same as console.log
- We need to handle the errors better. We havent gone over that yet so I will write something up and then you can use that as a template. 
- This seems to be in the `waitForNavigation` section. There is not much we can do to ovoid a timeout but we can handle it better. Its being caught but then just logged and its not making its way to our error handler so its not being listed as an error in the end. So if we werent logging at a debug level we would never see this error.
```
{"level":"debug","message":"Error fetching data for NO2: Navigation timeout of 30000 ms exceeded","name":"TimeoutError","stack":"TimeoutError: Navigation timeout of 30000 ms exceeded\n    at new Deferred (file:///home/christian/git/caparker/openaq-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:56:34)\n    at Deferred.create (file:///home/christian/git/caparker/openaq-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:18:16)\n    at new LifecycleWatcher (file:///home/christian/git/caparker/openaq-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/LifecycleWatcher.js:62:46)\n    at CdpFrame.goto (file:///home/christian/git/caparker/openaq-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:133:29)\n    at CdpFrame.<anonymous> (file:///home/christian/git/caparker/openaq-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:94:27)\n    at CdpPage.goto (file:///home/christian/git/caparker/openaq-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:563:43)\n    at fetchParameterData (file:///home/christian/git/caparker/openaq-fetch/src/adapters/delhi.js:79:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 1)\n    at async fetchAllParametersData (file:///home/christian/git/caparker/openaq-fetch/src/adapters/delhi.js:120:19)"}
````
- And I still see the highcharts error. This is happening because highcharts is not defined anywhere in your code. My guess is that the package needs to be installed and then imported into the adapter.
```
{"level":"debug","message":"Error fetching data for PM25: Highcharts is not defined","name":"ReferenceError","stack":"ReferenceError: Highcharts is not defined\n    at evaluate (evaluate at fetchParameterData (file:///home/christian/git/caparker/openaq-fetch/src/adapters/delhi.js:91:29), <anonymous>:1:20)\n    at #evaluate (file:///home/christian/git/caparker/openaq-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:219:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (file:///home/christian/git/caparker/openaq-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:114:16)\n    at async IsolatedWorld.evaluate (file:///home/christian/git/caparker/openaq-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:121:16)\n    at async CdpFrame.evaluate (file:///home/christian/git/caparker/openaq-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/api/Frame.js:340:20)\n    at async CdpPage.evaluate (file:///home/christian/git/caparker/openaq-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:801:20)\n    at async fetchParameterData (file:///home/christian/git/caparker/openaq-fetch/src/adapters/delhi.js:91:18)\n    at async Promise.all (index 0)\n    at async fetchAllParametersData (file:///home/christian/git/caparker/openaq-fetch/src/adapters/delhi.js:120:19)"}
```
- And then we are getting the following errors from the formatting
```
{"level":"info","message":"delhi-nct - 144 occurrences of instance.parameter is not one of enum values: pm25,pm10,no2,so2,o3,co,bc,no,nox,pm1"}
{"level":"info","message":"delhi-nct - 144 occurrences of instance.unit is not one of enum values: µg/m³,ppm"}
```
These errors are making there way to our error handler so that is great but they seem avoidable.

**Comment by russbiggs** [comment]
My two cents without looking at the code, but since i did the initial research on this source:
Puppeteer seems like a really heavyweight solution for this source and is likely the source of the slowness. Since the data are availalbe inline in the page, there shouldnt be any need to use a headless browser and wait for all the JS and rendering. Simply fetching the page and finding the data arrays in the page content e.g. 
```js
}, {*/
  name: 'Ammonia',
   data: [84.6,88.9,104.7,100.2,97.5,100.7,99.6,94.9,83.6,61.1,53.0,42.5,37.6,34.2,36.3,45.0,55.0,54.0,52.6,59.9,59.2,62.1,58.4]
   }]


```

With a lightweight parser will likely be much faster and simpler.

**Comment by majesticio** [comment]
I updated the package-lock, I am hoping some mismatch was causing issues as it seems to run fine on my end. You have both noted this might not be the best way to fetch from this provider and I will review it going forward. @caparker `Highcharts` is defined within the script with puppeteer and should resolve itself if the version is correct... ie if puppeteer is not working properly it won't find / define `Highcharts`

**Comment by majesticio** [comment]
The previous commit `613595b0b2a8d6183fe86ed20968e66451b52201` was returning more data for me. This was functioning on my end, however the adapter is slow and concerns have been expressed about its implementation. Closing, but may be of use for someone who can do it better.

**Pull request closed without merging**
