### PR TITLE
Signicode develop

### LINKED ISSUE #452: Investigate memory issues on fetch
We've seen a repeating failure mode where the fetch instance will run out of memory. Logs look look like 

```
> openaq-fetch@0.1.0 start /app
> node index.js

2018-01-28T21:31:09.829Z - info: Skipping inactive source: Buenos Aires
2018-01-28T21:31:09.833Z - info: Skipping inactive source: Dr. Raphael E. Arku and Colleagues
2018-01-28T21:31:09.833Z - info: Skipping inactive source: Punjabi Bagh
2018-01-28T21:31:09.833Z - info: Skipping inactive source: Mandir Marg
2018-01-28T21:31:09.833Z - info: Skipping inactive source: RK Puram
2018-01-28T21:31:09.833Z - info: Skipping inactive source: Anand Vihar
2018-01-28T21:31:09.834Z - info: Skipping inactive source: Mosecom
2018-01-28T21:31:09.834Z - info: Skipping inactive source: Spartan
2018-01-28T21:31:09.900Z - info: Connected to database.
2018-01-28T21:31:10.039Z - info: Database migrations are handled, ready to roll!
2018-01-28T21:31:10.040Z - info: Running all fetch tasks.
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

<--- Last few GCs --->

   89591 ms: Mark-sweep 1293.0 (1434.9) -> 1292.9 (1434.9) MB, 1603.4 / 0 ms [allocation failure] [GC in old space requested].
   91204 ms: Mark-sweep 1292.9 (1434.9) -> 1292.9 (1434.9) MB, 1613.1 / 0 ms [allocation failure] [GC in old space requested].
   92872 ms: Mark-sweep 1292.9 (1434.9) -> 1292.3 (1434.9) MB, 1668.0 / 0 ms [last resort gc].
   94512 ms: Mark-sweep 1292.3 (1434.9) -> 1292.1 (1434.9) MB, 1640.0 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1e07949c9e59 <JS Object>
    1: __push [/app/node_modules/csv-parse/lib/index.js:286] [pc=0x46e997523c3] (this=0x192287b067d1 <JS Object>,line=0x278a8d36dc01 <JS Array[24]>)
    2: __write [/app/node_modules/csv-parse/lib/index.js:496] [pc=0x46e9974f7de] (this=0x192287b067d1 <JS Object>,chars=0x278a8d00b499 <Very long string[196057]>,end=0x1e0794904299 <false>)
    3: /* anonymous */ [/app/node_modules/csv-parse/lib/sy...
```

With https://github.com/openaq/openaq-fetch/commit/2ced514e9661bb6c93d101fa0799abbe522cfa1d, the memory is up to 3200 for the container which is a fair amount, but we're still hitting limits. 

My guess is that one of the big sources (my guess is EEA) is doing a big update at this point and our system is trying to pull it all in. Not sure how to best handle this. 

To examine this a bit further, I added 

`console.log(source.name, (JSON.stringify(data).length / 1024).toFixed(2));` to https://github.com/openaq/openaq-fetch/blob/develop/fetch.js#L161 to get a rough size of the data coming back from the adapters. Results of that below, sizes should be in KB. Note that when I ran this on my local machine (this was for all sources), all the EEA sources failed for some reason, which is interesting in of itself.

```
StateAir_AbuDhabi 8.92
StateAir_Dhaka 8.84
Guangzhou 7.88
Shenyang 7.86
StateAir_Manama 17.59
Beijing US Embassy 8.08
Bosnia 15.29
Australia - Tasmania 24.48
Chengdu 7.85
Shanghai 7.87
StateAir_Bogota 8.82
Slovenian Environment Agency 2.87
StateAir_KuwaitCity 8.92
StateAir_Ulaanbaatar 8.96
StateAir_JakartaSouth 9.02
StateAir_Addis_Ababa_Central 9.13
StateAir_Kampala 8.85
StateAir_Mumbai 8.81
StateAir_Hanoi 8.87
StateAir_Addis_Ababa_School 9.10
StateAir_Pristina 8.89
StateAir_JakartaCentral 9.07
StateAir_Chennai 8.83
StateAir_Lima 8.87
Ho Chi Minh City 9.10
StateAir_Kolkata 8.84
StateAir_Colombo 8.85
Bosnia_Tuzlanski 7.87
StateAir_Kathmandu 18.14
Thailand 77.83
Bozhou 4.52
Arpae Emilia-Romagna 47.33
StateAir_Hyderabad 8.88
Chizhou 7.26
Lu'an 8.31
Norway 48.14
Anqing 7.71
Xuancheng 6.16
Wuhu 8.03
StateAir_PhoraDurbar 18.39
Huangshan 7.09
Huaibei 7.35
Suzhou 6.83
StateAir_NewDelhi 8.89
Chuzhou 4.86
Bengbu 13.76
Ma'anshan 11.44
Fuyang 6.57
Andalucia 0.03
Tongling 14.02
Hefei 19.98
Peru Clima 0.03
Chile - SINCA 74.78
Huainan 14.08
DEFRA 139.45
CPCB 155.53
Sweden 220.91
ARPALAZIO 1735.44
Sao Paulo 0.03
AirNow 86.75
Netherlands 99.12
Richards Bay 378.47
Israel 7604.79
```

So nothing above seems super huge give we have a machine with ~3GB RAM. Using HEAD on the EEA objects like

`curl -I http://discomap.eea.europa.eu/map/fme/latest/FR_PM10.csv`

we can see that these are often around 5 MB, but that's right as I checked it. I bet there are big spikes when more data is added.

Open to suggestions here. I kinda sorta like the simplicity of fetch at the moment, but part of me wonders if we should use this as a reason to move to something like Lambda function to kick off fetch -> Lambda functions for each adapter -> SNS or SQS or Kinesis for each fetch result -> some worker to get the data into database and S3.

### PR DESCRIPTION
**Pull request by jflasher**
Fixes #452 .

The change adds the option to expose a streamed version of the adapter data via the new fetchStream method. It also allows handling of that fetched data in fetch.js.

In streamed mode, the data is parsed and saved into the database already during downloading of the source, which greatly reduced memory consumption, since data is never fully aggregated into arrays kept in memory.

If the adapted does not support streaming (does not export the new method), the processed data is turned into stream and at least the fetch.js part of processing is not consuming extra memory.

Note: work was originally done in https://github.com/openaq/openaq-fetch/pull/479 but created this branch to make a few additional changes

### CODE REVIEW

**Comment by jflasher** [comment]
@MichalCz just ran this on staging and got the following error. Trying to reproduce locally, but wanted to flag in case you immediately know the issue.

```
2018-04-25T14:31:47.148Z - error: Error during fetching of data sources.
TypeError: "n" argument must be a positive number
    at DataStream.setMaxListeners (events.js:83:11)
    at DataStream.setMaxListeners (/app/node_modules/scramjet-core/lib/util/promise-transform-stream.js:102:38)
    at DataStream.setOptions (/app/node_modules/scramjet-core/lib/util/promise-transform-stream.js:96:18)
    at /app/fetch.js:247:10
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by MichalCz** [comment]
Yes... PSQL_POOL_MAX is an environment variable - I hadn't had that set so it defaulted to 10.

Add this:
```javascript
 .setOptions({maxParallel: +(process.env.PSQL_POOL_MAX || 10)})
```

It'll cast the string to integer.

**Comment by jflasher** [comment]
Worked, thanks!

**Comment by MichalCz** [comment]
No probs. :)

**Comment by nickolasclarke** [comment]
I'm polluting the comment stream here, but super stoked to see this get merged with `master` so that we can get #453 online! Can't wait to see that massive hunk of East Asia light up on the map. Great work both of you!

**Pull request merged**
