### PR TITLE
Correct tz handling for Dutch data. Fix #50

### LINKED ISSUE #50: NL adapter date looks to be off by one hour
According to http://www.timeanddate.com/worldclock/netherlands/amsterdam, should be +1 UTC, but recent data looks like 

```json
{
"_id": "56744fa651dc60c200e1969d",
"date": {
"utc": "2015-12-18T19:00:00.000Z",
"local": "2015-12-18T19:00:00+00:00"
},
"parameter": "so2",
"location": "Amsterdam-Hoogtij",
"value": 2.3,
"unit": "µg/m³",
"city": "Amsterdam",
"coordinates": {
"latitude": 52.428,
"longitude": 4.77348
},
"country": "NL"
}
```

### PR DESCRIPTION
**Pull request by olafveerman**

### CODE REVIEW

**Comment by olafveerman** [comment]
cc @jflasher @dolugen

**Comment by jflasher** [comment]
We'll need to go back and resave all the previous values. Should we wait to pull this in until then or handle them separately?

**Comment by olafveerman** [comment]
We can handle this separately, right? We'd do check whether the timestamps are the same update accordingly?

**Comment by dolugen** [comment]
@olafveerman That sounds good to me.

**Comment by jflasher** [comment]
Looks good, opened https://github.com/openaq/openaq-fetch/issues/91 to handle older values, pulling this in once tests pass.

**Pull request merged**
